config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  root 'events#index'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
	
	after_create :participation_send

	def participation_send
		UserMailer.participation_email(self).deliver_now
	end

end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances
	belongs_to :admin, class_name: "User"
	has_many :users, through: :attendances
	validates :start_date, presence: true
	validate :start_in_the_future
	validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
	validate :modulo_5
	validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000 }
	validates :location, presence: true

	def start_in_the_future
		if start_date.to_date < DateTime.now.to_date
			errors.add(:start_date, "can't be in the past")
		end
	end

	def modulo_5
		if duration % 5 != 0
			errors.add(:duration, "must be multiple of 5")
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances
	has_many :events
	has_many :events, through: :attendances
	
	validates :first_name, presence: true
	validates :last_name, presence: true
	
	after_create :welcome_send

	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper

	before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
	def create
    @events = Event.new('title' => params[:title], 'description' => params[:description])
	end
	
	def index
		@events = Event.all
	end

	def secret

	end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="card-body"> 
<% Event.all %>



<div class="jumbotron" style="text-align: center">
<div class="container">
<h1> <a class="display-4" style="color:rgb(255,255,255)" >EVENTBRITE </a> </h1>
<h2> <a class="display-4" style="color:rgb(255,255,255)" >Le site exclusif des meilleurs events !</a> </h2>
</div>
</div>

<div class="card-deck">
  <div class="card">
    <img class="card-img-top" src="https://duberguenardaupebroque.files.wordpress.com/2013/03/les-compagnons-du-boitchu-defendent-la-veritable-saucisse-de-montbeliard-fj.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">La Fête de la saucisse</h5>
      <p class="card-text">La Fête de la Saucisse se prépare. La Confrérie Gourmande et Joviale de la Saucisse à Grenade fêtera son 20° anniversaire, dimanche 20 mai. Comme chaque année, le chapitre se tiendra à la salle des fêtes de Grenade.</p>
      <p class="card-text"><small class="text-muted">Mardi 23 Decembre 2019</small></p>
      <button type="button" class="btn btn-dark">Voir l'event</button>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.southwesttimes.com/wp-content/uploads/2018/05/Chief-Boyd-horizontal.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Bal des Pompiers de Brive la Gaillarde</h5>
      <p class="card-text">Au programme : bonne humeur, accueil chaleureux, ambiance de village, bal populaire...</p>
      <p class="card-text"><small class="text-muted">Samedi 21 Novembre 2019</small></p>
      <button type="button" class="btn btn-dark">Voir l'event</button>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="http://data0.eklablog.com/evelaw/mod_article5528311_5.jpg?4531" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Fêtes des Berlouffes a Wattrelos</h5>
      <p class="card-text">La fête des Berlouffes est la plus grande manifestation populaire de Wattrelos. Elle commémore un épisode sanglant des guerres de religions ...</p>
      <p class="card-text"><small class="text-muted">Samedi 28 Novembre 2019</small></p>
      <button type="button" class="btn btn-dark">Voir l'event</button>
    </div>
  </div>
</div>




</div>

app/views/events/new.html.erb
<h2 style="text-align:center;">Crée ton event </h2>

<div class="card mb-3">
  <img class="card-img-top" src="https://www.ucb.ac.uk/content/images/courses/hospitality-tourism-events/events-management-3.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">A toi de jouer et de créer le prochain event du siecle !</h5>
    <p class="card-text">Choisis d'abord la ville ou tu veux organiser un new event.</p>
   

    <div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text" for="inputGroupSelect01">Ville</label>
  </div>
  <select class="custom-select" id="inputGroupSelect01">
    <option selected>Choose...</option>
    <option value="1">Lille</option>
    <option value="2">Paris</option>
    <option value="3">Aix-en-provence</option>
    <option value="4">Marseille</option>
    <option value="5">Nantes</option>
    <option value="6">Lyon</option>
    <option value="7">Bordeaux</option>
    <option value="8">Montpellier</option>
  </select>

  <button type="button" class="btn btn-outline-secondary">Entrer</button>
</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    <title>EVENTBRITE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <header>
  <div class="navbar">
  <div class="navbar_left">
    <nav class="stroke">
    <ul class=nav nav-pills nav-fill>
      <li class="nav-item">
      <%= link_to "Accueil", events_path, class:"nav-link active text-white" %> </li>
      <li class="nav-item">
      <%= link_to "Créer un nouvel Event", new_event_path, class:"nav-link active text-white" %> </li>    
  </div>
  </ul>
    

      <% if user_signed_in? %>
      
      <div class="navbar_right">

      <ul class=nav nav-pills>
      <li class="nav-item">
      <button type="button" class="btn btn-dark btn-sm">
      <%= current_user.first_name %>
      </button>
      </li>
        
        
        <li class="nav-item">
        <button type="button" class="btn btn-dark btn-sm"> <%= link_to "Edit email / password", edit_user_registration_path %></button>
         
        </li>

        <li class="nav-item">
        <button type="button" class="btn btn-dark btn-sm"><%= link_to "Deconnexion", destroy_user_session_path, method: :delete %></button>
        </li>
    
      <% else %>
        
      <div class="text-right"> 
        <button type="button" class="btn btn-outline-secondary btn-sm">
          <%= link_to "Connexion", new_user_session_path %>
        </button>
        
    
       
        <button type="button" class="btn btn-outline-secondary btn-sm">
          <%= link_to "Inscription", new_user_registration_path %>
          </button>
      </div>
    
      <% end %>
    </ul>
    </div>
    
     

    </nav>

    
  </div>
  </header>
  </head>
  <body>
    <%= yield %>
  </body>

  <footer id="footer" class="clearfix">
  <div id="footer-widgets">

    <div class="container">

    <div id="footer-wrapper">

      <div class="row">
        <div class="col-sm-6 col-md-2">
          <div id="meta-3" class="widget widgetFooter widget_meta">
          <h4 class="widgettitle">Notre site:</h4>
          <ul>
         <li><a href="#"><i class="fa fa-home fa-fw"></i> Accueil</a></li>
        <li><a href="privacypolicy.php"><i class="fa fa-link"></i> Privacy Policy</a></li>
        <li><a href="#"><i class="fa fa-envelope fa-fw"></i> Contact Us</a></li>
         </ul>
</div>      </div> <!-- end widget1 -->

        <div class="col-sm-6 col-md-2">
              <div id="recent-posts-3" class="widget widgetFooter widget_recent_entries">
                <h4 class="widgettitle">Our social media :</h4>
                <ul>
      <li>
         <a href="https://www.facebook.com/mr.dauod" target="_blank"><i class="fa fa-facebook"></i> Facebook</a>
      </li>
      <li>
          <a href="https://www.twitter.com/ayatquranCom" target="_blank"><i class="fa fa-twitter"></i> Twitter</a>
      </li>
      <li>
          <a href="http://www.youtube.com/user/sonsofye" target="_blank"><i class="fa fa-youtube"></i> Youtube</a>
       </li>
    </ul>
</div>            </div> <!-- end widget1 -->

        <div class="col-sm-6 col-md-4">
          <div id="meta-4" class="widget widgetFooter widget_meta">
          <h4 class="widgettitle">Subscribe :</h4>

          <div class="form-group">
            <div class="input-group">
              <input class="form-control" placeholder="Entre ton email .." type="text">
            </div>
          </div>

          <div class="form-group">
            <div class="input-group">
              <input class="form-control" placeholder="Numero de mobile" type="text">
               <span class="input-group-btn">
                <button class="btn btn-primary" type="button">Subscribe !</button>
              </span>
            </div>
          </div>


          </div>
         </div> <!-- end widget1 -->

        <div class="col-sm-6 col-md-4">
          <div id="search-3" class="widget widgetFooter widget_search"><h4 class="widgettitle">Rechercher un Event :</h4>

            <div class="form-group">
                            <label class="control-label">Keyword :</label>
                            <div class="input-group">
      
                              <input class="form-control" placeholder="Keyword for search ..." type="text">
                               <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">Search !</button>
                              </span>
                            </div>
                          </div>

            </div>            </div> <!-- end widget1 -->

      </div> <!-- end .row -->

    </div> <!-- end #footer-wrapper -->

    </div> <!-- end .container -->
  </div> <!-- end #footer-widgets -->

  <div id="sub-floor">
    <div class="container">
      <div class="row">
        <div class="col-md-4 copyright">
         Copy right for Ocece © 2020
        </div>
        <div class="col-md-4 col-md-offset-4 attribution">
         Developer by  <a target="_blank" href="#">Faploo team</a> .
        </div>
      </div> <!-- end .row -->
    </div>
  </div>

</footer>



</html>

app/views/users/user.show.html.erb
<h2>Connexion</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>